micronaut:
    application:
        name: micro-naut
    server:
        port: 8053
endpoints:
    routes:
        enabled: true
        sensitive: false
    metrics:
        enabled: true
        sensitive: false
    all:
        enabled: true
        sensitive: false
datasources:
    default:
        url: jdbc:h2:mem:micro-naut;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: "micro-naut"
        driverClassName: org.h2.Driver
