micronaut:
    application:
        name: micro-naut
    server:
        port: 8053
endpoints:
    routes:
        enabled: true
        sensitive: false
    metrics:
        enabled: true
        sensitive: false
    all:
        enabled: true
        sensitive: false
datasources:
    default:
        url: ${MICRO_POC_JDBC_URL:`jdbc:mysql://localhost:3306/micro-naut`}
        username: ${MICRO_POC_JDBC_USERNAME:`root`}
        password: ${MICRO_POC_JDBC_PASSWORD:`root`}
        driverClassName: ${MICRO_POC_JDBC_DRIVER:`com.mysql.jdbc.Driver`}
jpa:
    default:
        packages-to-scan:
            - 'micro.naut.entities'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
